name: Build project

on:
  push:
    branches: [ main ]

  schedule:
  - cron: "0 5 * * wed"
  
  workflow_dispatch:

jobs:
  linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Check out scripts
      uses: actions/checkout@v2
      
    - name: Download tags
      run: git fetch --prune --unshallow

    - name: Show available storage
      shell: bash
      run: df -h
      
      # This cleans up some space that we might need, maybe in the future more is required as chromium gets larger
    - name: Free up some disk space
      run: sudo rm -rf /usr/share/dotnet
    
    - name: Show available storage
      shell: bash
      run: df -h

    - name: Download last release hashes
      shell: bash
      run: curl -L "https://github.com/$GITHUB_REPOSITORY/releases/latest/download/SHA256SUMS" > SHA256SUMS || true
      working-directory: linux
      
    - name: Runnning build/generation script
      shell: bash
      run: |
        sudo bash ./generate_everything.sh
      working-directory: linux
        
    - name: Generate tag name
      run: echo "TAG_NAME=$(date +%F-%H-%M)" >> $GITHUB_ENV    
      working-directory: linux
        
    - uses: actions/upload-artifact@v2
      with:
        name: linux-zip
        path: linux/subresource_filter_tools_linux-x64.zip

    - uses: actions/upload-artifact@v2
      with:
        name: SHA256SUMS-linux
        path: linux/SHA256SUMS

    - uses: actions/upload-artifact@v2
      with:
        name: releasemd-linux
        path: linux/release.md
  
    - name: List chromium output directory
      shell: bash
      run: sudo find chromium/src/out
      if: always()

    - name: Show available storage
      shell: bash
      run: df -h
      if: always()
