name: Build project

on:
  push:
    branches: [ main ]

  schedule:
  - cron: "0 15 * * wed"
  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out scripts
      uses: actions/checkout@v2
      
    - name: Download tags
      run: git fetch --prune --unshallow

    - name: Show available storage
      shell: bash
      run: df -h
      
    - name: Free up 24GB of disk space
      run: sudo rm -rf /usr/share/dotnet
    
    - name: Show available storage
      shell: bash
      run: df -h
        
    - name: Download last release hashes
      shell: bash
      run: curl "https://github.com/$GITHUB_REPOSITORY/releases/latest/download/SHA256SUMS" > SHA256SUMS
      
    - name: Runnning build/generation script
      shell: bash
      run: |
        sudo bash ./generate_everything.sh
        
    - name: Generate tag name
      run: echo "TAG_NAME=$(date +%F-%H-%M)" >> $GITHUB_ENV    
      
    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: |
             subresource_filter_tools_linux-x64.zip
             SHA256SUMS
        tag_name: ${{ env.TAG_NAME }}
        name: "Automated build"
        fail_on_unmatched_files: true
        body_path: release.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: List chromium output directory
      shell: bash
      run: sudo find chromium/src/out
      if: always()
