name: Build project

on:
  workflow_dispatch:

jobs:
  windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show disk usage
        run: fsutil volume diskfree ((get-location).Drive.Name + ":")

      - name: Show all disks
        run: Get-PSDrive

      # Install the Windows 10 SDK, choose a compatible version from here: https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/
      - name: Install Windows 10 SDK
        run: |
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2164145" -OutFile "winsdksetup.exe"
          Start-Process -Wait -NoNewWindow -FilePath cmd -ArgumentList "/c", "winsdksetup.exe", "-features", "+", "-quiet"

      # Install "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" and set it up as described in the "Setting up Windows" section
      - name: Install Visual Studio Community 2019 Build Tools
        continue-on-error: true
        run: |
          choco install visualstudio2019community --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended --includeOptional --passive --locale en-US"

      - name: Show disk usage
        run: fsutil volume diskfree ((get-location).Drive.Name + ":")

      - name: Run build script
        run: .\build_windows.ps1
        working-directory: windows

      - name: Show disk usage
        run: fsutil volume diskfree ((get-location).Drive.Name + ":")
        if: ${{ always() }}

      - name: Show all disks
        run: Get-PSDrive
        if: ${{ always() }}

      - uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: windows/zucchini_windows-x64.zip

